"""MLproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v2P-JOUnBjJ0pQXaYPhEIwBAiHz5LZy6
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import os
import json

with open(os.path.join(os.path.dirname(__file__), '..', 'config.json')) as f:
    config = json.load(f)

dataset_11 = config["dataset_11"]
test = config["test"]

train_dataset = tf.keras.utils.image_dataset_from_directory(
    dataset_11,
    labels='inferred',
    label_mode='categorical',
    image_size=(224, 224),     #128 pixel size for greater accuracy
    batch_size=32
)

test_dataset = tf.keras.utils.image_dataset_from_directory(
    test,
    labels='inferred',
    label_mode='categorical',
    image_size=(224, 224),
    batch_size=32
)

#EDA - number of images in each class

class_counts = {cls: len(os.listdir(os.path.join(dataset_11, cls))) for cls in os.listdir(dataset_11)}

plt.bar(class_counts.keys(), class_counts.values(), color='skyblue')
plt.title('Class Distribution')
plt.xlabel('Tumor Type')
plt.ylabel('Number of Images')
plt.xticks(rotation=10)
plt.grid(axis='y')
plt.savefig('distribution.png')
plt.show()

#EDA - sample images
class_names = ['glioma', 'meningioma', 'notumor', 'pituitary']
found_classes = set()
images_to_show = []

# Loop through dataset to find one image per class
for images, labels in train_dataset:
    label_indices = tf.argmax(labels, axis=1)
    for i in range(len(label_indices)):
        class_idx = label_indices[i].numpy()
        if class_idx not in found_classes:
            found_classes.add(class_idx)
            images_to_show.append((images[i].numpy().astype("uint8"), class_idx))
        if len(found_classes) == len(class_names):
            break
    if len(found_classes) == len(class_names):
        break

# Display the collected images
plt.figure(figsize=(12, 8))
for i, (img, class_idx) in enumerate(images_to_show):
    plt.subplot(1, 4, i + 1)
    plt.imshow(img)
    plt.title(class_names[class_idx])
    plt.axis("off")
plt.tight_layout()
plt.savefig('display.png')
plt.show()

#EDA - image shape
for images, labels in train_dataset.take(1):
    print(f"Image shape: {images[0].shape}")

#Improve training stability and reduce overfitting:

model = tf.keras.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),  # <-- changed to 224x224
    layers.BatchNormalization(),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(224, (3, 3), activation='relu'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(224, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(4, activation='softmax')
])

model.summary()

# Compile the model
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),  # use CategoricalCrossentropy for one-hot labels
    metrics=['accuracy']
)

#checkpoint = tf.keras.callbacks.ModelCheckpoint('best_model.h5', save_best_only=True)
checkpoint = tf.keras.callbacks.ModelCheckpoint('best_weights.weights.h5', save_best_only=True, save_weights_only=True)
reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3)

# Train the model using dataset directly
history = model.fit(
    train_dataset,
    validation_data=test_dataset,
    epochs=50,
    callbacks=[reduce_lr, checkpoint]
)

#evaluate the model
plt.plot(history.history['accuracy'], label='accuracy')
plt.plot(history.history['val_accuracy'], label = 'val_accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.ylim([0.5, 1])
test_loss, test_acc = model.evaluate(test_dataset, verbose=2)
plt.legend(loc='lower right')
plt.savefig('evaluation.png')

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
with open('cnn_model_quantized.tflite', 'wb') as f:
    f.write(tflite_model)

print("Quantized TFLite model saved as cnn_model_quantized.tflite")

